runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/angularTestApplication/index.html
  upload: dist/angularTestApplication/index.html

- url: /
  static_dir: dist/angularTestApplication